### ISSUE TITLE
Provide example config.ini file

### ISSUE THREAD

**Issue by elainethale** [Smart-DS/R2PD#2]
Either just a template in the repo, or a way to dump a template in a user-specified location (via the CLI)

**Comment by MRossol** [comment]
see [R2PD/R2PD/library/config.ini](https://github.com/Smart-DS/R2PD/blob/master/R2PD/library/config.ini)

**Comment by elainethale** [comment]
I tried size = 5GB and R2PD barfed:

```
Traceback (most recent call last):
  File "/home/ehale/envs/r2pd/bin/R2PD", line 10, in <module>
    sys.exit(main())
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/R2PD/cli.py", line 85, in main
    repo = DRPower.connect(config=ds_config)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/R2PD/datastore.py", line 498, in connect
    local_cache = InternalDataStore.connect(config=config)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/R2PD/datastore.py", line 198, in connect
    size = float(size)
ValueError: could not convert string to float: '5GB'
```

**Comment by MRossol** [comment]
the config is expecting a float in GB. I can try to create a smart parser to parse the size from a string...

**Comment by MRossol** [comment]
Added comments to .ini and implemented @elainethale's fix
