### ISSUE TITLE
'InternalDataStore' object has no attribute 'test_cache'

### ISSUE THREAD

**Issue by elainethale** [Smart-DS/R2PD#7]
When I comment out the Issue #6 offending code and run 

```bash
python R2PD/cli.py -ds $CONFIG_FILE -n 28.442 -80.812 -t solar -te 1/1/2000 1/1/2020 -o $OUT_DIR power -c 10.0 actual
```

on the Peregrine set-up explained in #6 (and on elaine_debug), I get the following output and error message:

```python
(r2pd) [ehale@n2184 FAASSTeR]$ python ../R2PD/R2PD/cli.py -ds /home/ehale/r2pd_config.ini -n 28.442 -80.812 -t solar -te 1/1/2000 1/1/2020 -o reserves/data_out/ power -c 10.0 actual                                                                                         
DEBUG:__main__:Connecting to DRPower                                                                                                   
DEBUG:R2PD.datastore:Connecting to InternalDataStore                                                                                   
DEBUG:__main__:Determining local cache status                                                                                          
DEBUG:__main__:Getting nodes                                                                                                           
DEBUG:__main__:Getting temporal parameters                                                                                             
/home/ehale/R2PD/R2PD/nearestnodes.py:52: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead. 
  lat_lon = r_left.as_matrix(['latitude', 'longitude'])                                                                                
/home/ehale/R2PD/R2PD/nearestnodes.py:60: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead. 
  node_lat_lon = nodes_left.as_matrix(['latitude', 'longitude'])                                                                       
Traceback (most recent call last):                                                                                                     
  File "../R2PD/R2PD/cli.py", line 234, in <module>                                                                                    
    main()
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)                                                                                                  
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                            
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                            
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)                                                                                     
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)                                                                                   
  File "../R2PD/R2PD/cli.py", line 182, in actual                                                                                      
    nodes, _ = ctx.obj['repo'].get_resource(ctx.obj['nodes'])                                                                          
  File "/home/ehale/R2PD/R2PD/datastore.py", line 717, in get_resource                                                                 
    self.download_resource_data(dataset, site_ids, resource_type)                                                                      
  File "/home/ehale/R2PD/R2PD/datastore.py", line 638, in download_resource_data                                                       
    self._local_cache.test_cache(download_size)                                                                                        
AttributeError: 'InternalDataStore' object has no attribute 'test_cache'
```

**Comment by MRossol** [comment]
typo, should be test_cache_size, fixed on commit [4914f97](https://github.com/Smart-DS/R2PD/commit/4914f97602006ca9015123c085859074f056bc45)
