### ISSUE TITLE
KeyError in resourcedata.extract_data

### ISSUE THREAD

**Issue by elainethale** [Smart-DS/R2PD#8]
If I comment out all offending Issue #6 lines, then I get this error:

```
(r2pd) [ehale@n2184 FAASSTeR]$ python ../R2PD/R2PD/cli.py -ds /home/ehale/r2pd_config.ini -n 28.442 -80.812 -t solar -te 1/1/2000 1/1/2020 -o reserves/data_out/ power -c 10.0 actual
DEBUG:__main__:Connecting to DRPower
DEBUG:R2PD.datastore:Connecting to InternalDataStore
DEBUG:__main__:Determining local cache status
DEBUG:__main__:Getting nodes
DEBUG:__main__:Getting temporal parameters
/home/ehale/R2PD/R2PD/nearestnodes.py:52: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  lat_lon = r_left.as_matrix(['latitude', 'longitude'])
/home/ehale/R2PD/R2PD/nearestnodes.py:60: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  node_lat_lon = nodes_left.as_matrix(['latitude', 'longitude'])
DEBUG:R2PD.datastore:Making sure there is room in the local cache for 0.08 GB
DEBUG:R2PD.datastore:Downloading 10 power sites
Traceback (most recent call last):
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../R2PD/R2PD/cli.py", line 234, in <module>
    main()
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "../R2PD/R2PD/cli.py", line 183, in actual
    nodes.get_power(ctx.obj['out_ts_params'], shaper=ctx.obj['shaper'])
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 526, in get_power
    node.get_power(temporal_params, shaper=shaper)
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 141, in get_power
    power_data = self._resource.power_data
  File "/home/ehale/R2PD/R2PD/resourcedata.py", line 284, in power_data
    power_data = self._resources[0].power_data
  File "/home/ehale/R2PD/R2PD/resourcedata.py", line 137, in power_data
    power_data = self.extract_data('power_data')
  File "/home/ehale/R2PD/R2PD/resourcedata.py", line 122, in extract_data
    data['time'] = pds.to_datetime(data['time'].str.decode('utf-8'))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'time'
```

**Comment by MRossol** [comment]
fixed in commit [293264b](https://github.com/Smart-DS/R2PD/commit/293264b7faed7f326c8b472baebdd904fca1c890)
