### ISSUE TITLE
Assert error on resolution of solar data

### ISSUE THREAD

**Issue by elainethale** [Smart-DS/R2PD#9]
```python
print_cli_call_and_output(r2pd_command + \
                          ['-ds','/home/ehale/r2pd_config.ini',
                           '-n',test_plant.latitude,test_plant.longitude,
                           '-t','solar',
                           '-te','1/1/2012','12/1/2012',
                           '-o',out_dir,
                           'power',
                           '-c',test_plant.unit_nameplate_capacity_mw,
                           'actual'])
```

Yields:
```bash
python /home/ehale/R2PD/R2PD/cli.py -ds /home/ehale/r2pd_config.ini -n 28.442 -80.812 -t solar -te 1/1/2012 12/1/2012 -o reserves/data_out power -c 10.0 actual

Local Cache Initialized: Maximum size = 1000.00 GB Current size = 0.03 GB Cached wind data = 0.00 GB Cached solar data = 0.03 GB
/home/ehale/R2PD/R2PD/nearestnodes.py:52: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  lat_lon = r_left.as_matrix(['latitude', 'longitude'])
/home/ehale/R2PD/R2PD/nearestnodes.py:60: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  node_lat_lon = nodes_left.as_matrix(['latitude', 'longitude'])
Traceback (most recent call last):
  File "/home/ehale/R2PD/R2PD/cli.py", line 225, in <module>
    main()
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ehale/R2PD/R2PD/cli.py", line 176, in actual
    nodes.get_power(ctx.obj['out_ts_params'], shaper=ctx.obj['shaper'])
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 526, in get_power
    node.get_power(temporal_params, shaper=shaper)
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 148, in get_power
    self.power = shaper(power_data, temporal_params)
  File "/home/ehale/R2PD/R2PD/library/shapers.py", line 37, in __call__
    ts_tempparams = TemporalParameters.infer_params(ts)
  File "/home/ehale/R2PD/R2PD/tshelpers.py", line 68, in infer_params
    ts_params.infer_resolution(ts)
  File "/home/ehale/R2PD/R2PD/tshelpers.py", line 86, in infer_resolution
    assert len(resolution) == 1, 'Time resolution is not constant! Found time resolutions:\n{}\nfrom timeseries:\n{}'.format(resolution, ts)
AssertionError: Time resolution is not constant! Found time resolutions:
[  300000000000 86700000000000]
from timeseries:
                     Power  Clearsky_Power
Timestamp                                 
2007-01-01 00:00:00  0.000           0.000
2007-01-01 00:05:00  0.000           0.000
2007-01-01 00:10:00  0.000           0.000
2007-01-01 00:15:00  0.000           0.000
2007-01-01 00:20:00  0.000           0.000
2007-01-01 00:25:00  0.000           0.000
2007-01-01 00:30:00  0.000           0.000
2007-01-01 00:35:00  0.000           0.000
2007-01-01 00:40:00  0.000           0.000
2007-01-01 00:45:00  0.000           0.000
2007-01-01 00:50:00  0.000           0.000
2007-01-01 00:55:00  0.000           0.000
2007-01-01 01:00:00  0.000           0.000
2007-01-01 01:05:00  0.000           0.000
2007-01-01 01:10:00  0.000           0.000
2007-01-01 01:15:00  0.000           0.000
2007-01-01 01:20:00  0.000           0.000
2007-01-01 01:25:00  0.000           0.000
2007-01-01 01:30:00  0.000           0.000
2007-01-01 01:35:00  0.000           0.000
2007-01-01 01:40:00  0.000           0.000
2007-01-01 01:45:00  0.000           0.000
2007-01-01 01:50:00  0.000           0.000
2007-01-01 01:55:00  0.000           0.000
2007-01-01 02:00:00  0.000           0.000
2007-01-01 02:05:00  0.000           0.000
2007-01-01 02:10:00  0.000           0.000
2007-01-01 02:15:00  0.000           0.000
2007-01-01 02:20:00  0.000           0.000
2007-01-01 02:25:00  0.000           0.000
...                    ...             ...
2012-12-30 21:30:00  0.184           0.984
2012-12-30 21:35:00  0.160           0.904
2012-12-30 21:40:00  0.136           0.820
2012-12-30 21:45:00  0.120           0.740
2012-12-30 21:50:00  0.100           0.652
2012-12-30 21:55:00  0.080           0.576
2012-12-30 22:00:00  0.068           0.496
2012-12-30 22:05:00  0.052           0.412
2012-12-30 22:10:00  0.036           0.328
2012-12-30 22:15:00  0.020           0.240
2012-12-30 22:20:00  0.008           0.156
2012-12-30 22:25:00  0.000           0.060
2012-12-30 22:30:00  0.000           0.000
2012-12-30 22:35:00  0.000           0.000
2012-12-30 22:40:00  0.000           0.000
2012-12-30 22:45:00  0.000           0.000
2012-12-30 22:50:00  0.000           0.000
2012-12-30 22:55:00  0.000           0.000
2012-12-30 23:00:00  0.000           0.000
2012-12-30 23:05:00  0.000           0.000
2012-12-30 23:10:00  0.000           0.000
2012-12-30 23:15:00  0.000           0.000
2012-12-30 23:20:00  0.000           0.000
2012-12-30 23:25:00  0.000           0.000
2012-12-30 23:30:00  0.000           0.000
2012-12-30 23:35:00  0.000           0.000
2012-12-30 23:40:00  0.000           0.000
2012-12-30 23:45:00  0.000           0.000
2012-12-30 23:50:00  0.000           0.000
2012-12-30 23:55:00  0.000           0.000

[630720 rows x 2 columns]
```

**Comment by elainethale** [comment]
Tried explicitly setting the resolution, but it still barfs:

```python
print_cli_call_and_output(r2pd_command + \
                          ['-ds','/home/ehale/r2pd_config.ini',
                           '-n',test_plant.latitude,test_plant.longitude,
                           '-t','solar',
                           '-te','1/1/2012','12/1/2012',
                           '-tr','5 min',
                           '-o',out_dir,
                           'power',
                           '-c',test_plant.unit_nameplate_capacity_mw,
                           'actual'])
```

```bash
print_cli_call_and_output(r2pd_command + \

                          ['-ds','/home/ehale/r2pd_config.ini',

                           '-n',test_plant.latitude,test_plant.longitude,

                           '-t','solar',

                           '-te','1/1/2012','12/1/2012',

                           '-tr','5 min',

                           '-o',out_dir,

                           'power',

                           '-c',test_plant.unit_nameplate_capacity_mw,

                           'actual'])

python /home/ehale/R2PD/R2PD/cli.py -ds /home/ehale/r2pd_config.ini -n 28.442 -80.812 -t solar -te 1/1/2012 12/1/2012 -tr "5 min" -o reserves/data_out power -c 10.0 actual

Local Cache Initialized: Maximum size = 1000.00 GB Current size = 0.03 GB Cached wind data = 0.00 GB Cached solar data = 0.03 GB
/home/ehale/R2PD/R2PD/nearestnodes.py:52: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  lat_lon = r_left.as_matrix(['latitude', 'longitude'])
/home/ehale/R2PD/R2PD/nearestnodes.py:60: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  node_lat_lon = nodes_left.as_matrix(['latitude', 'longitude'])
Traceback (most recent call last):
  File "/home/ehale/R2PD/R2PD/cli.py", line 226, in <module>
    main()
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ehale/envs/r2pd/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ehale/R2PD/R2PD/cli.py", line 177, in actual
    nodes.get_power(ctx.obj['out_ts_params'], shaper=ctx.obj['shaper'])
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 526, in get_power
    node.get_power(temporal_params, shaper=shaper)
  File "/home/ehale/R2PD/R2PD/powerdata.py", line 148, in get_power
    self.power = shaper(power_data, temporal_params)
  File "/home/ehale/R2PD/R2PD/library/shapers.py", line 37, in __call__
    ts_tempparams = TemporalParameters.infer_params(ts)
  File "/home/ehale/R2PD/R2PD/tshelpers.py", line 68, in infer_params
    ts_params.infer_resolution(ts)
  File "/home/ehale/R2PD/R2PD/tshelpers.py", line 86, in infer_resolution
    assert len(resolution) == 1, 'Time resolution is not constant! Found time resolutions:\n{}\nfrom timeseries:\n{}'.format(resolution, ts)
AssertionError: Time resolution is not constant! Found time resolutions:
[  300000000000 86700000000000]
from timeseries:
                     Power  Clearsky_Power
Timestamp                                 
2007-01-01 00:00:00  0.000           0.000
2007-01-01 00:05:00  0.000           0.000
2007-01-01 00:10:00  0.000           0.000
2007-01-01 00:15:00  0.000           0.000
2007-01-01 00:20:00  0.000           0.000
2007-01-01 00:25:00  0.000           0.000
2007-01-01 00:30:00  0.000           0.000
2007-01-01 00:35:00  0.000           0.000
2007-01-01 00:40:00  0.000           0.000
2007-01-01 00:45:00  0.000           0.000
2007-01-01 00:50:00  0.000           0.000
2007-01-01 00:55:00  0.000           0.000
2007-01-01 01:00:00  0.000           0.000
2007-01-01 01:05:00  0.000           0.000
2007-01-01 01:10:00  0.000           0.000
2007-01-01 01:15:00  0.000           0.000
2007-01-01 01:20:00  0.000           0.000
2007-01-01 01:25:00  0.000           0.000
2007-01-01 01:30:00  0.000           0.000
2007-01-01 01:35:00  0.000           0.000
2007-01-01 01:40:00  0.000           0.000
2007-01-01 01:45:00  0.000           0.000
2007-01-01 01:50:00  0.000           0.000
2007-01-01 01:55:00  0.000           0.000
2007-01-01 02:00:00  0.000           0.000
2007-01-01 02:05:00  0.000           0.000
2007-01-01 02:10:00  0.000           0.000
2007-01-01 02:15:00  0.000           0.000
2007-01-01 02:20:00  0.000           0.000
2007-01-01 02:25:00  0.000           0.000
...                    ...             ...
2012-12-30 21:30:00  0.184           0.984
2012-12-30 21:35:00  0.160           0.904
2012-12-30 21:40:00  0.136           0.820
2012-12-30 21:45:00  0.120           0.740
2012-12-30 21:50:00  0.100           0.652
2012-12-30 21:55:00  0.080           0.576
2012-12-30 22:00:00  0.068           0.496
2012-12-30 22:05:00  0.052           0.412
2012-12-30 22:10:00  0.036           0.328
2012-12-30 22:15:00  0.020           0.240
2012-12-30 22:20:00  0.008           0.156
2012-12-30 22:25:00  0.000           0.060
2012-12-30 22:30:00  0.000           0.000
2012-12-30 22:35:00  0.000           0.000
2012-12-30 22:40:00  0.000           0.000
2012-12-30 22:45:00  0.000           0.000
2012-12-30 22:50:00  0.000           0.000
2012-12-30 22:55:00  0.000           0.000
2012-12-30 23:00:00  0.000           0.000
2012-12-30 23:05:00  0.000           0.000
2012-12-30 23:10:00  0.000           0.000
2012-12-30 23:15:00  0.000           0.000
2012-12-30 23:20:00  0.000           0.000
2012-12-30 23:25:00  0.000           0.000
2012-12-30 23:30:00  0.000           0.000
2012-12-30 23:35:00  0.000           0.000
2012-12-30 23:40:00  0.000           0.000
2012-12-30 23:45:00  0.000           0.000
2012-12-30 23:50:00  0.000           0.000
2012-12-30 23:55:00  0.000           0.000

[630720 rows x 2 columns]
```

**Comment by elainethale** [comment]
c125782b14b077ee4d6aad96ed652c48a889875c fixes the issue.
